<?php
session_start();
require_once 'conexao.php';
require_once 'includes/flash.php';
$pdo->exec("CREATE TABLE IF NOT EXISTS redefinicoes_senha_usuarios (id BIGINT AUTO_INCREMENT PRIMARY KEY,usuario_id INT NOT NULL,token_hash CHAR(64) NOT NULL UNIQUE,expira_em DATETIME NOT NULL,usado_em DATETIME NULL,criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,INDEX idx_reset_usuario(usuario_id),INDEX idx_reset_usuario_expira(expira_em)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
$token=$_GET['token']??$_POST['token']??'';$valid=false;$row=null;
if($token){$h=hash('sha256',$token);$s=$pdo->prepare('SELECT r.*,u.email FROM redefinicoes_senha_usuarios r JOIN usuarios u ON u.id=r.usuario_id WHERE r.token_hash=? AND r.usado_em IS NULL AND r.expira_em>NOW() AND u.ativo=1 LIMIT 1');$s->execute([$h]);$row=$s->fetch();$valid=(bool)$row;}
if($_SERVER['REQUEST_METHOD']==='POST'&&$valid){
  $senha=$_POST['senha']??'';$conf=$_POST['confirmar']??'';
  if(!preg_match('/^(?=.*\d)(?=.*[^A-Za-z0-9]).{8,}$/',$senha))flash('error','Use pelo menos 8 caracteres, 1 número e 1 caractere especial.');
  elseif($senha!==$conf)flash('error','As senhas não coincidem.');
  else{$pdo->beginTransaction();$pdo->prepare('UPDATE usuarios SET senha=? WHERE id=?')->execute([password_hash($senha,PASSWORD_DEFAULT),$row['usuario_id']]);$pdo->prepare('UPDATE redefinicoes_senha_usuarios SET usado_em=NOW() WHERE id=?')->execute([$row['id']]);$pdo->commit();flash('success','Senha redefinida. Faça login com a nova senha.');header('Location: login.php');exit;}
}
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Nova senha | Espaço Aura</title><link rel="icon" type="image/png" sizes="512x512" href="img/favicon-aura.png"><link rel="shortcut icon" href="img/favicon.ico"><link rel="stylesheet" href="css/style.css"></head><body><header class="header"><div class="container nav"><a href="index.php" class="brand"><img src="img/logo-aura-oficial.png" alt="Espaço Aura"></a><a href="login.php" class="back-link">← Login</a></div></header><main class="form-page"><div class="form-container"><p class="eyebrow">PORTAL DA EQUIPE</p><h1>Crie uma nova senha</h1><?php mostrarFlash();?><?php if(!$valid):?><div class="alert error" data-popup="1">Este link é inválido ou expirou. Solicite um novo link.</div><p style="text-align:center;margin-top:20px"><a href="esqueci-senha.php"><b>Solicitar novo link</b></a></p><?php else:?><form method="post" class="form-card"><input type="hidden" name="token" value="<?=htmlspecialchars($token)?>"><label>Nova senha<input type="password" name="senha" minlength="8" autocomplete="new-password" required></label><p class="muted">Mínimo 8 caracteres, 1 número e 1 caractere especial.</p><label>Confirmar nova senha<input type="password" name="confirmar" minlength="8" autocomplete="new-password" required></label><button class="btn btn-full">Salvar nova senha</button></form><?php endif;?></div></main><script src="js/app.js"></script></body></html>
