<?php
session_start();require_once '../conexao.php';require_once '../includes/flash.php';require_once '../includes/validation.php';
if(!empty($_SESSION['paciente_id'])){header('Location: '.(($_GET['next']??'')==='agendar'?'../agendamento.php':'index.php'));exit;}
$erro='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 $nome=trim($_POST['nome']??'');$email=filter_var(trim($_POST['email']??''),FILTER_VALIDATE_EMAIL);$tel=somenteDigitos($_POST['telefone']??'');$nasc=$_POST['nascimento']??'';$senha=$_POST['senha']??'';$conf=$_POST['confirmar']??'';
 if(mb_strlen($nome)<3||!$email||!telefoneValido($tel)||!$nasc)$erro='Preencha seus dados corretamente.';
 elseif(!preg_match('/^(?=.*\d)(?=.*[^A-Za-z0-9]).{8,}$/',$senha))$erro='A senha precisa ter no mínimo 8 caracteres, 1 número e 1 caractere especial.';
 elseif($senha!==$conf)$erro='As senhas não coincidem.';
 else try{$s=$pdo->prepare('INSERT INTO pacientes(nome,email,telefone,nascimento,senha) VALUES(?,?,?,?,?)');$s->execute([$nome,$email,$tel,$nasc,password_hash($senha,PASSWORD_DEFAULT)]);flash('success','Cadastro realizado. Entre com seu e-mail e senha.');header('Location: login.php');exit;}catch(Throwable $e){$erro='Não foi possível criar a conta. Verifique se o e-mail já está cadastrado.';}
}
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cadastro do paciente | Espaço Aura</title><link rel="icon" type="image/png" sizes="512x512" href="../img/favicon-aura.png"><link rel="shortcut icon" href="../img/favicon.ico"><link rel="stylesheet" href="../css/style.css"></head><body><header class="header"><div class="container nav"><a href="../index.php" class="brand"><img src="../img/logo-aura-oficial.png" alt="Espaço Aura"></a><a class="back-link" href="../index.php">← Início</a></div></header><main class="form-page"><div class="form-container"><p class="eyebrow">ÁREA DO PACIENTE</p><h1>Crie sua conta</h1><?php if($erro):?><div class="alert error" data-popup="1"><?=htmlspecialchars($erro)?></div><?php endif;?><form method="post" class="form-card"><label>Nome completo<input name="nome" required value="<?=htmlspecialchars($_POST['nome']??'')?>"></label><label>E-mail<input type="email" name="email" required value="<?=htmlspecialchars($_POST['email']??'')?>"></label><label>Telefone<input name="telefone" type="tel" inputmode="numeric" data-phone maxlength="15" required placeholder="(11) 99999-9999" value="<?=htmlspecialchars($_POST['telefone']??'')?>"></label><label>Data de nascimento<input type="date" name="nascimento" required max="<?=date('Y-m-d')?>" value="<?=htmlspecialchars($_POST['nascimento']??'')?>"></label><label>Senha<input type="password" name="senha" minlength="8" autocomplete="new-password" required><small>Mínimo 8 caracteres, 1 número e 1 caractere especial.</small></label><label>Confirmar senha<input type="password" name="confirmar" autocomplete="new-password" required></label><button class="btn btn-full">Criar conta</button><p class="muted" style="text-align:center;margin-top:15px">Já possui conta? <a href="login.php"><b>Entrar</b></a></p></form></div></main><script src="../js/app.js"></script></body></html>
